import { useEffect, useState } from 'react';
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  CircularProgress,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Avatar,
  FormHelperText,
} from '@mui/material';
import {
  CheckCircle as ApproveIcon,
  Cancel as RejectIcon,
  Delete as DeleteIcon,
} from '@mui/icons-material';
import { faceRegistrationApi, departmentApi } from '@/api';
import { FaceRegistration, ApproveRegistrationDto, Department } from '@/types';
import { format } from 'date-fns';
import toast from 'react-hot-toast';

export default function PendingRegistrations() {
  const [registrations, setRegistrations] = useState<FaceRegistration[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [loading, setLoading] = useState(true);
  const [approveDialog, setApproveDialog] = useState<{ open: boolean; registration: FaceRegistration | null }>({
    open: false,
    registration: null,
  });
  const [rejectDialog, setRejectDialog] = useState<{ open: boolean; registration: FaceRegistration | null }>({
    open: false,
    registration: null,
  });

  const [approveData, setApproveData] = useState<ApproveRegistrationDto>({
    email: '',
    password: '',
    role: 'EMPLOYEE',
    position: '',
    departmentId: '',
    phone: '',
  });

  const [rejectReason, setRejectReason] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [registrationsData, departmentsData] = await Promise.all([
        faceRegistrationApi.getPending(),
        departmentApi.getAll(),
      ]);
      setRegistrations(registrationsData);
      setDepartments(departmentsData.filter(d => d.isActive));
    } catch (error) {
      toast.error('Gagal memuat data');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const loadPendingRegistrations = async () => {
    try {
      setLoading(true);
      const data = await faceRegistrationApi.getPending();
      setRegistrations(data);
    } catch (error) {
      toast.error('Gagal memuat data pendaftaran');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleApproveClick = (registration: FaceRegistration) => {
    setApproveDialog({ open: true, registration });
    setApproveData({
      email: '',
      password: '',
      role: 'EMPLOYEE',
      position: '',
      departmentId: '',
      phone: '',
    });
  };

  const handleRejectClick = (registration: FaceRegistration) => {
    setRejectDialog({ open: true, registration });
    setRejectReason('');
  };

  const handleApprove = async () => {
    if (!approveDialog.registration) return;

    // Validate departmentId is required
    if (!approveData.departmentId || !approveData.departmentId.trim()) {
      toast.error('Departemen harus dipilih');
      return;
    }

    try {
      setSubmitting(true);
      // Send only role and departmentId (email & password will be auto-generated by backend)
      const dataToSend: any = {
        role: approveData.role || 'EMPLOYEE',
        departmentId: approveData.departmentId.trim(),
      };

      await faceRegistrationApi.approve(approveDialog.registration.id, dataToSend);
      toast.success('Pendaftaran berhasil disetujui dan akun dibuat');
      setApproveDialog({ open: false, registration: null });
      loadPendingRegistrations();
    } catch (error) {
      console.error(error);
    } finally {
      setSubmitting(false);
    }
  };

  const handleReject = async () => {
    if (!rejectDialog.registration) return;

    if (!rejectReason || rejectReason.length < 10) {
      toast.error('Alasan penolakan minimal 10 karakter');
      return;
    }

    try {
      setSubmitting(true);
      await faceRegistrationApi.reject(rejectDialog.registration.id, { reason: rejectReason });
      toast.success('Pendaftaran berhasil ditolak');
      setRejectDialog({ open: false, registration: null });
      loadPendingRegistrations();
    } catch (error) {
      console.error(error);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id: string, name: string) => {
    if (!confirm(`Hapus pendaftaran dari ${name}?`)) return;

    try {
      await faceRegistrationApi.delete(id);
      toast.success('Pendaftaran berhasil dihapus');
      loadPendingRegistrations();
    } catch (error) {
      console.error(error);
    }
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box>
      <Typography variant="h4" gutterBottom fontWeight="bold">
        Pendaftaran Wajah Pending
      </Typography>
      <Typography variant="body1" color="textSecondary" sx={{ mb: 3 }}>
        Kelola pendaftaran wajah yang menunggu persetujuan
      </Typography>

      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell><strong>Foto</strong></TableCell>
              <TableCell><strong>Nama</strong></TableCell>
              <TableCell><strong>Status</strong></TableCell>
              <TableCell><strong>Tanggal Daftar</strong></TableCell>
              <TableCell align="center"><strong>Aksi</strong></TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {registrations.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} align="center">
                  <Typography variant="body2" color="textSecondary" sx={{ py: 4 }}>
                    Tidak ada pendaftaran yang menunggu persetujuan
                  </Typography>
                </TableCell>
              </TableRow>
            ) : (
              registrations.map((registration) => (
                <TableRow key={registration.id} hover>
                  <TableCell>
                    <Avatar
                      src={registration.faceImageUrl}
                      alt={registration.name}
                      sx={{ width: 50, height: 50 }}
                    >
                      {registration.name.charAt(0).toUpperCase()}
                    </Avatar>
                  </TableCell>
                  <TableCell>{registration.name}</TableCell>
                  <TableCell>
                    <Chip
                      label={registration.status}
                      color="warning"
                      size="small"
                    />
                  </TableCell>
                  <TableCell>
                    {format(new Date(registration.createdAt), 'dd MMM yyyy HH:mm')}
                  </TableCell>
                  <TableCell align="center">
                    <Box sx={{ display: 'flex', gap: 1, justifyContent: 'center' }}>
                      <Button
                        size="small"
                        variant="contained"
                        color="success"
                        startIcon={<ApproveIcon />}
                        onClick={() => handleApproveClick(registration)}
                      >
                        Setuju
                      </Button>
                      <Button
                        size="small"
                        variant="contained"
                        color="error"
                        startIcon={<RejectIcon />}
                        onClick={() => handleRejectClick(registration)}
                      >
                        Tolak
                      </Button>
                      <Button
                        size="small"
                        variant="outlined"
                        color="error"
                        startIcon={<DeleteIcon />}
                        onClick={() => handleDelete(registration.id, registration.name)}
                      >
                        Hapus
                      </Button>
                    </Box>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </TableContainer>

      <Box sx={{ mt: 2 }}>
        <Typography variant="body2" color="textSecondary">
          Total: {registrations.length} pendaftaran menunggu
        </Typography>
      </Box>

      {/* Approve Dialog */}
      <Dialog open={approveDialog.open} onClose={() => setApproveDialog({ open: false, registration: null })} maxWidth="sm" fullWidth>
        <DialogTitle>Setujui Pendaftaran</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="textSecondary" sx={{ mb: 1 }}>
            Buat akun untuk: <strong>{approveDialog.registration?.name}</strong>
          </Typography>

          <Typography variant="caption" color="info.main" sx={{ mb: 3, display: 'block', p: 1.5, bgcolor: 'info.lighter', borderRadius: 1 }}>
            ℹ️ Email dan password akan otomatis di-generate oleh sistem
          </Typography>

          <FormControl fullWidth sx={{ mb: 2 }}>
            <InputLabel>Role</InputLabel>
            <Select
              value={approveData.role}
              label="Role"
              onChange={(e) => setApproveData({ ...approveData, role: e.target.value as 'ADMIN' | 'EMPLOYEE' })}
            >
              <MenuItem value="EMPLOYEE">Employee</MenuItem>
              <MenuItem value="ADMIN">Admin</MenuItem>
            </Select>
          </FormControl>

          <FormControl fullWidth required error={!approveData.departmentId && departments.length > 0}>
            <InputLabel>Departemen</InputLabel>
            <Select
              value={approveData.departmentId}
              label="Departemen"
              onChange={(e) => setApproveData({ ...approveData, departmentId: e.target.value })}
            >
              {departments.map((dept) => (
                <MenuItem key={dept.id} value={dept.id}>
                  {dept.name}
                </MenuItem>
              ))}
            </Select>
            {departments.length === 0 && (
              <FormHelperText error>
                Belum ada departemen aktif. Silakan tambahkan departemen terlebih dahulu.
              </FormHelperText>
            )}
          </FormControl>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setApproveDialog({ open: false, registration: null })} disabled={submitting}>
            Batal
          </Button>
          <Button onClick={handleApprove} variant="contained" color="success" disabled={submitting || departments.length === 0}>
            {submitting ? 'Memproses...' : 'Setujui & Buat Akun'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Reject Dialog */}
      <Dialog open={rejectDialog.open} onClose={() => setRejectDialog({ open: false, registration: null })} maxWidth="sm" fullWidth>
        <DialogTitle>Tolak Pendaftaran</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="textSecondary" sx={{ mb: 2 }}>
            Berikan alasan penolakan untuk: <strong>{rejectDialog.registration?.name}</strong>
          </Typography>

          <TextField
            fullWidth
            label="Alasan Penolakan"
            multiline
            rows={4}
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
            helperText="Minimal 10 karakter"
            required
            sx={{ mt: 1 }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setRejectDialog({ open: false, registration: null })} disabled={submitting}>
            Batal
          </Button>
          <Button onClick={handleReject} variant="contained" color="error" disabled={submitting}>
            {submitting ? 'Memproses...' : 'Tolak Pendaftaran'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
